### ISSUE TITLE
spaces at end of stem not being recognized

### ISSUE THREAD

**Issue by bdhrs** [digitalpalitools/inflection-generator#1]
examples 

"na "+"kaci pron"
"no "+"kaci pron"
"tuṇhī "+"ahosi aor"

these are producing results without spaces like
nakoci, nakāyaci, nakassāci, nakāsañci, nakiñci, nakāhici, nakesuci, nakehici, nakāyaci, nakesañci

those should be 
na koci, na kāyaci, na kassāci, na kāsañci, na kiñci, na kāhici, na kesuci, na kehici, na kāyaci, na kesañci

**Comment by parthopdas** [comment]
ad4092f4 and 8e392f3 should resolve this - please reactivate if not.
